// <auto-generated />

namespace Plumber.Framework
{
	public static class HttpStatuses
	{
    public static Pipe OK()
    { 
      return Custom(200, "OK");
    }

    public static Pipe MovedPermanently()
    { 
      return Custom(301, "MovedPermanently");
    }

    public static Pipe Found()
    { 
      return Custom(302, "Found");
    }

    public static Pipe NotModified()
    { 
      return Custom(304, "NotModified");
    }


    public static Pipe Custom(int statusCode, string statusMsg)
    {
      return ctx =>
      {
        ctx.Response.StatusCode = statusCode;
        ctx.Response.StatusMessage = statusMsg;

        return ctx;
      };
    }
	}
}
